### ISSUE TITLE
Windows implementation is not native

### ISSUE THREAD

**Issue by Mason-Chou** [repeats/SimpleNativeHooks#3]
Just read the implementation for Windows and it seems like it's relying on Program.exe running through the .NET's CLR (program is written in C#). 

There's ways to compile to .NET languages to native, but that feature is only on Windows 10 (and maybe future versions). Source: [.NET Native doc](https://docs.microsoft.com/en-us/dotnet/framework/net-native/)

I could be wrong, but I would like to hear how you would run this package on Windows without a .NET Framework installed on the Machine.

**Comment by hptruong93** [comment]
SetWindowsHookEx is also available through the Windows desktop API.
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowshookexa

With the absence of .NET framework, we simply need to translate the C# code (src/org/simplenativehooks/windows/nativecontent/Program.cs) to C++ code to use the native DLL and create a binary from there.
Are you looking for a solution that doesn't require .NET being installed?

**Comment by Mason-Chou** [comment]
In a sense, yes. 

I understand that you are calling Windows API by utilizing P/Invoke, so the performance should be close to native in this scenario. However, I would argue that Program.exe is still a CLR application.  

I don't think requiring a .NET installation can be considered "native" code as it introduces another dependency you need. For a simple key listener/mouse listener, the software should just use the API given by the operating system.

A better solution is to write a unmanaged C++ program that calls the Windows API. That's as close to native as you can get for Windows (as you don't need any dependencies). A nightmare to do as you probably would need to compile for multiple Windows version. 

Could just include your .NET Framework version for in your list of dependency and call it a day. For a simple project like this, I think you got your point across.

**Comment by hptruong93** [comment]
Yea I included the .NET framework version in the README.
As you mentioned, no point getting to involved into generating different binaries for different Windows versions.
